name: Build
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build images
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images
