name: Deploy CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy CI
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push CI
        if: github.ref == 'refs/heads/master'
        run: ./builder.bash push-ci
