name: Deploy CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy CI
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images
      - name: Push CI
        if: github.ref == 'refs/heads/master'
        run: ./builder.bash push-ci
