name: Push tagged
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "This workflow will build and push the versioned taged images to docker hub."
          echo "It only runs on pushes of tags."
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write VERSION file
        run: echo ${{ github.ref_name }} > VERSION
      - name: Output VERSION file
        run: cat ./VERSION
      - name: Build images
        run: ./builder.bash deploy-ci
      - name: Re tag images
        run: |
          docker tag addshore/dns-proxy-server:latest addshore/dns-proxy-server:${{ github.ref_name }}
          docker tag addshore/dns-proxy-server:latest-arm7x86 addshore/dns-proxy-server:${{ github.ref_name }}-arm7x86
          docker tag addshore/dns-proxy-server:latest-arm8x64 addshore/dns-proxy-server:${{ github.ref_name }}-arm8x64
      - name: List images
        run: docker images
      - name: List build files
        run: ls ./build

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - name: Build docs
        run: ./builder.bash docs

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Images
        run: |
          docker push addshore/dns-proxy-server:${{ github.ref_name }}
          docker push addshore/dns-proxy-server:${{ github.ref_name }}-arm7x86
          docker push addshore/dns-proxy-server:${{ github.ref_name }}-arm8x64

      - name: Extract changelog entry
        uses: kemayo/actions-recent-changelog@v1
        with:
          input: RELEASE-NOTES.md
          output: RECENT-CHANGES.md
      - name: Output RECENT-CHANGES.md
        run: cat ./RECENT-CHANGES.md

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RECENT-CHANGES.md
          files: |
            build/dns-proxy-server-linux-386-${{ github.ref_name }}.tgz
            build/dns-proxy-server-linux-amd64-${{ github.ref_name }}.tgz
            build/dns-proxy-server-linux-arm-${{ github.ref_name }}.tgz
            build/dns-proxy-server-linux-arm64-${{ github.ref_name }}.tgz

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs
          destination_dir: ${{ github.ref_name }}
          commit_message: Publishing docs for ${{ github.ref_name }}
