name: Push latest
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "This workflow will build and push the latest taged images to docker hub."
          echo "It only runs on pushes to the master branch."
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build images
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images
      - name: List build files
        run: ls ./build

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - name: Build docs
        run: ./builder.bash docs

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Images
        run: |
          docker push addshore/dns-proxy-server:latest
          docker push addshore/dns-proxy-server:latest-arm7x86
          docker push addshore/dns-proxy-server:latest-arm8x64

      - name: Deploy Github pages root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.github/gh-pages
          keep_files: true
          commit_message: Publishing updated root files
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs
          destination_dir: latest
          keep_files: true
          commit_message: Publishing docs for latest
