name: Push latest
on:
  push:
    branches:
      - master

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "This workflow will build and push the latest taged images to docker hub."
          echo "It only runs on pushes to the master branch."
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build images
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Images
        run: |
          docker push addshore/dns-proxy-server:latest
          docker push addshore/dns-proxy-server:latest-arm7x86
          docker push addshore/dns-proxy-server:latest-arm8x64
