name: Push latest
on:
  push:
    branches:
      - master

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build images
        run: ./builder.bash deploy-ci
      - name: List images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push CI
        run: ./builder.bash push-ci
