name: Test
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "This workflow will run the basic tests on pull requests, merges into master and all tags."
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker-compose up --build tests
